name: Chromatic

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["master"]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run:
          npm install --legacy-peer-deps
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: chpt_68142ee61976993
          buildScriptName: build-storybook
          workingDir: /.storybook
