name: Chromatic

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["master"]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: ['install-deps']
    steps:
#        with:
#          fetch-depth: 0
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: chpt_68142ee61976993
          buildScriptName: build-storybook
          workingDir: /config/storybook

  lint:
    runs-on: ubuntu-latest
    needs: [ 'install-deps' ]
    steps:
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss

  tests:
    runs-on: ubuntu-latest
    needs: [ 'install-deps' ]
    steps:
      - name: unit testing
        run: npm run unit
